# Generated by Django 4.1 on 2022-08-28 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('-created',), 'verbose_name_plural': 'Books'},
        ),
    ]
